# Generated by Django 6.1 on 2026-09-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_docs", models.TextField(blank=True, default="")),
                ("campaign_target", models.TextField(blank=True, default="")),
                (
                    "booking_link",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("ai_model", models.CharField(blank=True, default="", max_length=200)),
                (
                    "llm_api_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "llm_api_base",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "bettercontact_api_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "apollo_api_key",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "email_finder",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "operator_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "operator_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                ("accepted_legal_notice", models.BooleanField(default=False)),
                ("newsletter", models.BooleanField(default=False)),
                (
                    "mailbox_address",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "mailbox_password",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("smtp_host", models.CharField(blank=True, default="", max_length=200)),
                ("smtp_port", models.CharField(blank=True, default="", max_length=8)),
                ("imap_host", models.CharField(blank=True, default="", max_length=200)),
                ("imap_port", models.CharField(blank=True, default="", max_length=8)),
                ("signature", models.TextField(blank=True, default="")),
                (
                    "contacts_api_token",
                    models.CharField(blank=True, default="", max_length=500),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
