# Generated by Django 6.1 on 2026-09-05 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openoutreach_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='country_code',
            new_name='operator_country_code',
        ),
    ]
